### PR TITLE
fix: metadata and wording

### LINKED ISSUE #134: (Design QA) 計畫介紹頁面 Enhancement
Image

### LINKED ISSUE #138: (Design QA) search engine index issue
Image

### LINKED ISSUE #139: (Design QA) Update metadata

### PR DESCRIPTION
**Pull request by kylemocode**
## Why need this change? / Root cause:

- close #134 
- close #138 
- close #139 

## Changes made:

- update meta title for each pages
- add canonical URL for each pages
- wording change

## Test Scope / Change impact:

-

### CODE REVIEW

File: nextjs-app/app/about/overview/page.tsx [hunk 1]
```diff
@@ -5,17 +5,21 @@ import MarqueeImage from "@/components/pages/about/overview/MarqueeImage";
 import MonthlyMeetingRoles from "@/components/pages/about/overview/MonthlyMeetingRoles";
 import RecruitmentTargets from "@/components/pages/about/overview/RecruitmentTargets";
 import GroupsIntro from "@/components/pages/about/overview/GroupsIntro";
+import Routes from "@/constants/routes";
 import type { Metadata } from "next";
 
 export const metadata: Metadata = {
-  title: "計畫介紹",
+  title: "計畫介紹｜關於曼陀號",
```
Comment (gongtzuuuu) [inline nextjs-app/app/about/overview/page.tsx:12]: Should it be 計"劃"介紹 to keep the consistency?

Comment (kylemocode) [reply nextjs-app/app/about/overview/page.tsx]: updated [b69ce53](https://github.com/thementorship-tw/thementorship.tw/pull/141/commits/b69ce53325abc79a0525ba99aad5a76221559b7e)

**Review by ChengYiLin — APPROVED** [review]
